Fix typescript errors
Fixes typescript errors related to missing properties and default exports.
- Fixes error TS2339: Property 'full_name' does not exist on type 'SelectQueryError<"could not find the relation between equipment_withdrawals and user_id">'.
- Fixes error TS2353: Object literal may only specify known properties, and 'equipment_name' does not exist in type 'SetStateAction<Receipt>'.
- Fixes error TS2613: Module '"/dev-server/src/components/equipment/ScheduleModal"' has no default export. Did you mean to use 'import { ScheduleModal } from "/dev-server/src/components/equipment/ScheduleModal"' instead?
- Fixes error TS2613: Module '"/dev-server/src/components/equipment/ReturnModal"' has no default export. Did you mean to use 'import { ReturnModal } from "/dev-server/src/components/equipment/ReturnModal"' instead?